# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raymond Cheong Cano's Site
subtitle: Tech | Music | Sports
email: cheongcano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I think I'm unique...hopefully this site helps me show that.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rayraycano.github.io" # the base hostname & protocol for your site
twitter_username: rayraycano
github_username:  rayraycano
soundcloud_username: four-point-o 

# Build settings
markdown: kramdown
highlighter: rouge
